spring.application.name=backend
server.port=8081
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.4vuzmaf.mongodb.net/Smart-campus-operations-hub?retryWrites=true&w=majority&authSource=admin
jwt.secret=SmartCampusSecretKey2026SuperSecureRandomString
google.client.id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID_HERE}

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.security=DEBUG
